// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // input a number 
		int n = Integer.parseInt(args [0]);
        int lessorequal = 0;
        int grater = 0;

		//mathrandom N times
		for (int i = 0; i <= n; i++)  {
	    double random = Math.random ();
		
		//print the random number 
		if (random <= 0.5) {
			lessorequal ++;
		} else { 
			grater++;
		}
	}
	  // find the ratio
	  double ratio = (double) lessorequal / (double) grater;
     
      //print the results
	  System.out.println( "  > 0.5: " + grater + " times");
	  System.out.println( " <= 0.5: " + lessorequal + " times");

	  if (lessorequal > 0){
      System.out.println( " Ratio: " + ratio);
	}
}
}
 